Repository antidot-framework/antidot-starter, pull requests merged in 2021-01, with the labels that each got.

#21 Add php8 support
  composer.json
Labels: dependencies, enhancement

#22 Improving setup routes comments
  router/routes.php
Labels: documentation, enhancement

#24 bump framework and router to 0.2.0
  composer.json
Labels: dependencies
